export type DeviceAclEntry = {
  username: string;
  homeId: string;
  deviceId: string;
  nodeId: string;
};

export type ServiceAccounts = {
  gatewayUsername: string;
  simulatorUsername: string;
  simulatorHomeId: string;
};

type AclLine = { permission: "read" | "write" | "readwrite"; topic: string };

function topicMatches(pattern: string, topic: string): boolean {
  const p = pattern.split("/");
  const t = topic.split("/");
  for (let i = 0; i < p.length; i++) {
    if (p[i] === "#") return true;
    if (t[i] === undefined) return false;
    if (p[i] !== "+" && p[i] !== t[i]) return false;
  }
  return p.length === t.length;
}

export function parseAclFile(contents: string): Map<string, AclLine[]> {
  const map = new Map<string, AclLine[]>();
  let current: string | null = null;
  for (const raw of contents.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("user ")) {
      current = line.slice(5).trim();
      if (!map.has(current)) map.set(current, []);
      continue;
    }
    if (!current) continue;
    const m = line.match(/^topic\s+(readwrite|read|write)\s+(\S+)$/);
    if (!m) continue;
    map.get(current)!.push({
      permission: m[1] as AclLine["permission"],
      topic: m[2],
    });
  }
  return map;
}

export function aclAllows(
  acl: Map<string, AclLine[]>,
  username: string,
  access: "read" | "write",
  topic: string
): boolean {
  const lines = acl.get(username);
  if (!lines) return false;
  return lines.some((line) => {
    if (!topicMatches(line.topic, topic)) return false;
    if (line.permission === "readwrite") return true;
    return line.permission === access;
  });
}

export function buildAclFile(devices: DeviceAclEntry[], accounts: ServiceAccounts): string {
  const blocks: string[] = [
    "# Generated by scripts/mqtt-users.ts — do not edit by hand.",
    "# Default deny. A device may only write its own telemetry/state/ack/event and its",
    "# node availability topic, and may only read its own command topic.",
    "",
  ];

  for (const d of devices) {
    blocks.push(`user ${d.username}`);
    blocks.push(`topic write home/${d.homeId}/device/${d.deviceId}/telemetry`);
    blocks.push(`topic write home/${d.homeId}/device/${d.deviceId}/state`);
    blocks.push(`topic write home/${d.homeId}/device/${d.deviceId}/ack`);
    blocks.push(`topic write home/${d.homeId}/device/${d.deviceId}/event`);
    blocks.push(`topic write home/${d.homeId}/node/${d.nodeId}/availability`);
    blocks.push(`topic read home/${d.homeId}/device/${d.deviceId}/command`);
    blocks.push("");
  }

  blocks.push(`user ${accounts.gatewayUsername}`);
  blocks.push("topic read home/+/device/+/+");
  blocks.push("topic read home/+/node/+/availability");
  blocks.push("topic write home/+/device/+/command");
  blocks.push("");

  const home = accounts.simulatorHomeId;
  blocks.push(`user ${accounts.simulatorUsername}`);
  blocks.push(`topic write home/${home}/device/+/telemetry`);
  blocks.push(`topic write home/${home}/device/+/state`);
  blocks.push(`topic write home/${home}/device/+/ack`);
  blocks.push(`topic write home/${home}/device/+/event`);
  blocks.push(`topic write home/${home}/node/+/availability`);
  blocks.push(`topic read home/${home}/device/+/command`);
  blocks.push("");

  return blocks.join("\n");
}
